---
name: Samba NAS
version: 10.0.0-nas3
slug: sambanas
description: Expose Home Assistant disc with SMB/CIFS
url: https://github.com/dianlight/hassio-addons/tree/master/sambanas
codenotary: lucio.tarantino@gmail.com
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: system
boot: auto
init: false
hassio_api: true
host_network: true
map:
- config:rw
- ssl:rw
- addons:rw
- share:rw
- backup:rw
- media:rw
options:
  workgroup: WORKGROUP
  username: homeassistant
  password:
  allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
  moredisks:
  - "<PARTITION LABEL>"
  available_disks_log: false
  medialibrary:
    enable: false
    ssh_private_key: "<YOU SUPER SECRET PRIVATE KEY>"
  veto_files:
  - "._*"
  - ".DS_Store"
  - Thumbs.db
  - icon?
  - ".Trashes"
  compatibility_mode: false
  wsdd2: false
  autodiscovery: {}
  other_users: []
  acl: []
  interfaces: []
  mountoptions: "nosuid,relatime,noexec"
schema:
  workgroup: str
  username: str
  password: password
  moredisks:
  - str
  available_disks_log: bool?
  medialibrary:
    enable: bool?
    ssh_private_key: password?
  allow_hosts:
  - str
  veto_files:
  - str
  compatibility_mode: bool?
  wsdd2: bool?
  mqtt_enable: bool?
  mqtt_host: str?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_port: str?
  mqtt_topic: str?
  autodiscovery:
    disable_discovery: bool?
    disable_persistent: bool?
    disable_autoremove: bool?
  other_users:
    - username: str
      password: str
  acl:
    - share: str
      disabled: bool?
      users: 
      - str?
      timemachine: bool?
  interfaces:
  - str?   
  log_level: list(trace|debug|info|notice|warning|error|fatal)?   
  mountoptions: str


image: dianlight/{arch}-addon-sambanas
services:
- mqtt:want
udev: true
usb: true
host_dbus: true
kernel_modules: true
privileged:
- SYS_ADMIN
- SYS_RAWIO
- SYS_RESOURCE
- SYS_MODULE
full_access: true
devicetree: false
apparmor: true
host_ipc: true
#advanced: true

